- hosts: localhost
  pre_tasks:
    - name: Update apt
      become: true
      apt:
        force_apt_get: true
        update_cache: true
        state: present
      tags:
        - install
        - utilities
        - sqlite
  
  tasks:
    - name: Git config
      ansible.builtin.include_tasks:
        file: tasks/git-setup.yml
    - name: Core packages
      ansible.builtin.include_tasks:
        file: tasks/core-setup.yml
    - name: Node installation
      ansible.builtin.include_tasks:
        file: tasks/node-setup.yml
    - name: Zsh installation
      ansible.builtin.include_tasks:
        file: tasks/zsh-setup.yml
    - name: Neovim installation
      ansible.builtin.include_tasks:
        file: tasks/neovim-setup.yml
    - name: Dotfiles installation
      ansible.builtin.include_tasks:
        file: tasks/dotfiles-setup.yml
    - name: Pyenv installation
      ansible.builtin.include_tasks:
        file: tasks/pyenv-setup.yml
    - name: Go installation
      ansible.builtin.include_tasks:
        file: tasks/go-setup.yml
    - name: Utility tools
      ansible.builtin.include_tasks:
        file: tasks/utilities-setup.yml
      tags:
          - utilities
    - name: SQLite
      ansible.builtin.include_tasks:
        file: tasks/sqlite-install.yml
      tags:
          - sqlite
    - name: Docker
      ansible.builtin.include_tasks:
        file: tasks/docker-install.yml
      tags:
          - docker
