- hosts: localhost
  pre_tasks:
    - name: Update apt
      become: true
      apt:
        force_apt_get: true
        update_cache: true
        state: present
      tags:
        - install
  tasks:
    - include: tasks/git-setup.yml
