- hosts: localhost
  pre_tasks:
    - name: Update apt
      become: true
      apt:
        force_apt_get: true
        update_cache: true
        state: present
      tags:
        - install
  tasks:
    - name: Fresh install
      ansible.builtin.include_tasks:
        file: tasks/git-setup.yml
        file: tasks/core-setup.yml
