- hosts: localhost
  pre_tasks:
    - name: Update apt
      become: true
      apt:
        force_apt_get: true
        update_cache: true
        state: present
      tags:
        - install
  tasks:
    - name: Git config
      ansible.builtin.include_tasks:
        file: tasks/git-setup.yml
    - name: Core packages
      ansible.builtin.include_tasks:
        file: tasks/core-setup.yml
    - name: Zsh installation
      ansible.builtin.include_tasks:
        file: tasks/zsh-setup.yml
    - name: Neovim installation
      ansible.builtin.include_tasks:
        file: tasks/neovim-setup.yml
    - name: Dotfiles installation
      ansible.builtin.include_tasks:
        file: tasks/dotfiles-setup.yml
