- name: Install System Packages (build-essential, cmake)
  become: true
  apt:
    name: ["build-essential", "cmake"]
  tags:
    - install

- name: Install compiling tools (unzip, gettext)
  become: true
  apt:
    name: ["unzip", "gettext"]
  tags:
    - install

- name: Install System Packages
  become: true
  apt:
    name: ["curl", "htop"]
  tags:
    - install

- name: Install man pages
  become: true
  apt:
    name: ["manpages-posix", "manpages-dev", "man-db", "manpages-posix-dev"]
  tags:
    - install
