- name: Install Docker dependencies
  become: true
  apt:
    name: ["ca-certificates", "curl"]
  tags:
    - install
    - docker

- name: Add Docker's official GPG key
  become: true
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  tags:
    - install
    - docker

- name: Add Docker repository
  become: true
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    update_cache: yes
  tags:
    - install
    - docker

- name: Install Docker CE
  become: true
  apt:
    name: ["docker-ce", "docker-ce-cli"]
    state: present
  tags:
    - install
    - docker

- name: Add user to docker group
  user:
    name: "sampotter"
    groups: docker
    append: yes
  tags:
    - install
    - docker
