- name: Install stow
  become: true
  apt: name=stow
  tags:
    - install
- name: Clone dotfiles
  ansible.builtin.git:
    repo: 'git@github.com:stpotter16/dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
  tags:
    - install
