- name: Remove neovim
  shell: rm -rf ~/neovim
  tags:
    - install

- name: Get Packer
  ansible.builtin.git:
    repo: 'https://github.com/wbthomason/packer.nvim'
    dest: "{{ lookup('env', 'HOME') }}/.local/share/nvim/site/pack/packer/start/packer.nvim"
  tags:
    - install

- name: Clone Neovim
  ansible.builtin.git:
    repo: 'https://github.com/neovim/neovim.git'
    dest: "{{ lookup('env', 'HOME') }}/neovim"
  tags:
    - install

- name: Build Neovim
  shell: "cd {{ lookup('env', 'HOME') }}/neovim && git checkout stable && make"
  tags:
    - install

- name: Install Neovim
  become: true
  shell: "cd {{ lookup('env', 'HOME') }}/neovim && make install"
  tags:
    -install
